name: ElyInv
version: "0.1.0"
main: com.marrineer.elyInv.ElyInv
api-version: "1.21"
authors: [Marrineer]
website: https://guns.lol/marrineer
commands:
  elyinv:
    description: Main command for ElyInv plugin
    usage: /elyinv
    permission: elyinv.use

permissions:
  elyinv.use:
    description: Allows the player to use basic ElyInv commands
    default: true

  elyinv.admin:
    description: Allows access to ElyInv admin commands
    default: op
